# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2baf1afe32be23bccd333f2e427a32b134a918c30673c6131db991a867ebe878449a71d37b5857eface35c0e82b52bf40289285fd6589685ced3dbab213416b1

test:
  secret_key_base: c120ede6414d8b163f2da4363c6e059fd45a428e41047c469f2b9f2f13d393f810c5654f44876c8fa2437dd8ec68ea34bee917d168ae854d73a6fdfec562f54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
